# Generated by Django 5.0.2 on 2024-07-28 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='record5',
            name='child',
            field=models.CharField(default='2', max_length=100),
            preserve_default=False,
        ),
    ]
